<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button Configuracoes</name>
   <tag></tag>
   <elementGuidId>412d03fd-da37-4e58-8477-4c2c87270536</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fe.fe-settings</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='angular-boot-modules']/ul/li[2]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fe fe-settings</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;angular-boot-modules&quot;)/ul[1]/li[@class=&quot;drop-down&quot;]/a[1]/i[@class=&quot;fe fe-settings&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='angular-boot-modules']/ul/li[2]/a/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/nav/ul/li[2]/a/i</value>
   </webElementXpaths>
</WebElementEntity>
